@page = Page.find(71)
@view_cast = @page.view_cast if @page.view_cast_id.present?
@page_streams = @page.page_streams
@page.publish = @page.status == 'published'
@is_article_page = @page.template_page.name == "article"
@page_stream_narrative = @page.streams.where(title: "#{@page.id.to_s}_Story_Narrative").first
@page_stream_related = @page.streams.where(title: "#{@page.id.to_s}_Story_Related").first
@page_stream_related7c = @page_stream_related.page_streams.first
@page_stream_narrative7c = @page_stream_narrative.page_streams.first
exclude_view_casts = StreamEntity.view_casts.where(stream_id: [@page_stream_narrative.id, @page_stream_related.id]).pluck(:entity_value)
@all_cards = @site.view_casts.where.not(id: exclude_view_casts).where(is_autogenerated: false, template_card_id: TemplateCard.where.not(name: ['toParagraph', 'toStory'])).where(folder_id: @site.folders.active.where(ref_category_vertical_id: @page.series.id).pluck(:id)).order([updated_at: :desc, created_at: :desc])
@all_cards += @site.view_casts.where.not(id: exclude_view_casts).where(template_card_id: TemplateCard.where(name: "toStory")).where(is_autogenerated: true).where(folder_id: @site.folders.active.where(ref_category_vertical_id: @page.series.id).pluck(:id)).order([updated_at: :desc, created_at: :desc])