class AddColumn12323ToViewCast < ActiveRecord::Migration[5.1]
  def change
    add_column :view_casts, :is_autogenerated, :boolean, default: false

    ViewCast.where(id: Page.all.pluck(:view_cast_id)).update_all(is_autogenerated: true)
  end
end
